<?php

class m130423_121921_ngin extends CDbMigration {
  public function safeUp() {
    
    $this->execute("UPDATE `da_object_parameters` SET `id_object`=31, `id_parameter`=286, `id_parameter_type`=10, `sequence`=8, `name`='ngin.yiigin.DomainLocalizationVisualElement', `caption`='Доступные локализации', `field_name`='engine/admin/element/abstract/DomainLocalization.php', `add_parameter`=2, `default_value`=NULL, `not_null`=0, `sql_parameter`='DomainLocalization', `is_unique`=0, `group_type`=0, `need_locale`=0, `search`=0, `is_additional`=0, `hint`=NULL WHERE `da_object_parameters`.`id_object`=31 AND `da_object_parameters`.`id_parameter`=286");
    $this->execute("UPDATE `da_object_parameters` SET `id_object`=21, `id_parameter`=76, `id_parameter_type`=7, `sequence`=1, `name`='ngin.yiigin.objectParameter.typeObjectParameterWidget.TypeObjectParameterWidget', `caption`='Тип свойства', `field_name`='id_parameter_type', `add_parameter`=22, `default_value`='2', `not_null`=1, `sql_parameter`=NULL, `is_unique`=0, `group_type`=0, `need_locale`=0, `search`=0, `is_additional`=0, `hint`=NULL WHERE `da_object_parameters`.`id_object`=21 AND `da_object_parameters`.`id_parameter`=76");
    $this->execute("UPDATE `da_object_parameters` SET `id_object`=20, `id_parameter`=68, `id_parameter_type`=7, `sequence`=9, `name`='id_field_caption', `caption`='Свойство для отображения', `field_name`='id_field_caption', `add_parameter`=21, `default_value`='', `not_null`=0, `sql_parameter`='t.id_object=:id_instance', `is_unique`=0, `group_type`=0, `need_locale`=0, `search`=0, `is_additional`=0, `hint`='Значение данного свойства будет выводится в списке, когда экземпляр данного объекта будет выбираться в качестве свойства другого объекта' WHERE `da_object_parameters`.`id_object`=20 AND `da_object_parameters`.`id_parameter`=68");
    $this->execute("UPDATE `da_object_parameters` SET `id_object`=20, `id_parameter`=65, `id_parameter_type`=7, `sequence`=10, `name`='id_field_order', `caption`='Свойство для порядка', `field_name`='id_field_order', `add_parameter`=21, `default_value`='', `not_null`=0, `sql_parameter`='t.id_object=:id_instance', `is_unique`=0, `group_type`=0, `need_locale`=0, `search`=0, `is_additional`=0, `hint`='По умолчанию выводимые в системе администрирования экземпляры данного объекта будут упорядочены по этому свойству' WHERE `da_object_parameters`.`id_object`=20 AND `da_object_parameters`.`id_parameter`=65");
    $this->execute("UPDATE `da_object` SET `id_object`=21, `name`='Свойства объекта', `id_field_order`=77, `order_type`=1, `table_name`='da_object_parameters', `id_field_caption`=79, `object_type`=1, `folder_name`='', `parent_object`=20, `sequence`=2, `seq_start_value`=1500, `use_domain_isolation`=0, `id_object_handler`=NULL, `id_instance_class`=NULL, `field_caption`='caption', `yii_model`='ngin.models.object.ObjectParameter' WHERE `da_object`.`id_object`=21");
    $this->execute("DELETE FROM `da_php_script_type` WHERE `da_php_script_type`.`id_php_script_type`=407");
    $this->execute("UPDATE `da_object_parameters` SET `id_object`=66, `id_parameter`=420, `id_parameter_type`=7, `sequence`=7, `name`='ngin.yiigin.objectParameter.selectObjectParameterWidget.SelectObjectParameterWidget', `caption`='Параметр объекта', `field_name`='id_object_parameter', `add_parameter`=21, `default_value`='', `not_null`=0, `sql_parameter`='', `is_unique`=0, `group_type`=0, `need_locale`=0, `search`=0, `is_additional`=0, `hint`='' WHERE `da_object_parameters`.`id_object`=66 AND `da_object_parameters`.`id_parameter`=420");
    $this->execute("UPDATE `da_object` SET `id_object`=66, `name`='Колонка представления', `id_field_order`=419, `order_type`=1, `table_name`='da_object_view_column', `id_field_caption`=NULL, `object_type`=1, `folder_name`='', `parent_object`=63, `sequence`=9, `seq_start_value`=6000, `use_domain_isolation`=0, `id_object_handler`=NULL, `id_instance_class`=NULL, `field_caption`=NULL, `yii_model`='ngin.models.object.DaObjectViewColumn' WHERE `da_object`.`id_object`=66");
    $this->execute("DELETE FROM `da_php_script_type` WHERE `da_php_script_type`.`id_php_script_type`=421");
    $this->execute("UPDATE `da_object` SET `id_object`=93, `name`='Настройка загрузки файлов', `id_field_order`=NULL, `order_type`=1, `table_name`='da_file_upload_settings', `id_field_caption`=NULL, `object_type`=1, `folder_name`='', `parent_object`=1, `sequence`=33, `seq_start_value`=1, `use_domain_isolation`=0, `id_object_handler`=NULL, `id_instance_class`=NULL, `field_caption`=NULL, `yii_model`=NULL WHERE `da_object`.`id_object`=93");
    $this->execute("DELETE FROM `da_php_script_type` WHERE `da_php_script_type`.`id_php_script_type`=425");
    $this->execute("DELETE FROM `da_php_script_interface` WHERE `da_php_script_interface`.`id_php_script_interface`=12");
    $this->execute("DELETE FROM `da_php_script_interface` WHERE `da_php_script_interface`.`id_php_script_interface`=11");
    $this->execute("DELETE FROM `da_php_script_interface` WHERE `da_php_script_interface`.`id_php_script_interface`=10");
    $this->execute("UPDATE `da_object_parameters` SET `id_object`=20, `id_parameter`=151, `id_parameter_type`=10, `sequence`=19, `name`='perm', `caption`='Права доступа', `field_name`='ngin.yiigin.object.objectPermission.ObjectPermissionWidget', `add_parameter`=2, `default_value`='', `not_null`=0, `sql_parameter`='ObjectPermissionVisualElement', `is_unique`=0, `group_type`=0, `need_locale`=0, `search`=0, `is_additional`=0, `hint`='' WHERE `da_object_parameters`.`id_object`=20 AND `da_object_parameters`.`id_parameter`=151");
    $this->execute("UPDATE `da_object_parameters` SET `id_object`=20, `id_parameter`=62, `id_parameter_type`=10, `sequence`=15, `name`='representation', `caption`='Создать представление', `field_name`='ngin.yiigin.object.objectManageView.ObjectManageViewWidget', `add_parameter`=2, `default_value`='', `not_null`=0, `sql_parameter`='ObjectRepresentationVisualElement', `is_unique`=0, `group_type`=0, `need_locale`=0, `search`=0, `is_additional`=1, `hint`='' WHERE `da_object_parameters`.`id_object`=20 AND `da_object_parameters`.`id_parameter`=62");
    $this->execute("DELETE FROM `da_object_parameters` WHERE `da_object_parameters`.`id_object`=20 AND `da_object_parameters`.`id_parameter`=126");
    $this->execute("UPDATE `da_object_parameters` SET `id_object`=101, `id_parameter`=14, `id_parameter_type`=10, `sequence`=10, `name`='modules', `caption`='Модули', `field_name`='menu.yiigin.widgets.manageModule.ManageModuleWidget', `add_parameter`=2, `default_value`='', `not_null`=0, `sql_parameter`='SiteModuleTemplateListOfModule', `is_unique`=0, `group_type`=0, `need_locale`=0, `search`=0, `is_additional`=0, `hint`='' WHERE `da_object_parameters`.`id_object`=101 AND `da_object_parameters`.`id_parameter`=14");
    $this->execute("UPDATE `da_object` SET `id_object`=101, `name`='Наборы модулей', `id_field_order`=16, `order_type`=2, `table_name`='da_site_module_template', `id_field_caption`=13, `object_type`=1, `folder_name`='', `parent_object`=102, `sequence`=7, `seq_start_value`=1, `use_domain_isolation`=0, `id_object_handler`=NULL, `id_instance_class`=NULL, `field_caption`='name', `yii_model`='SiteModuleTemplate' WHERE `da_object`.`id_object`=101");
    $this->execute("UPDATE `da_object` SET `id_object`=89, `name`='Очистить кэш', `id_field_order`=NULL, `order_type`=1, `table_name`='yiigin/special/clearCache', `id_field_caption`=NULL, `object_type`=3, `folder_name`='', `parent_object`=3, `sequence`=2, `seq_start_value`=1, `use_domain_isolation`=0, `id_object_handler`=NULL, `id_instance_class`=NULL, `field_caption`=NULL, `yii_model`='' WHERE `da_object`.`id_object`=89");
    $this->execute("UPDATE `da_object` SET `id_object`=94, `name`='Логи', `id_field_order`=NULL, `order_type`=1, `table_name`='yiigin/special/logView', `id_field_caption`=NULL, `object_type`=3, `folder_name`='', `parent_object`=3, `sequence`=12, `seq_start_value`=1, `use_domain_isolation`=0, `id_object_handler`=NULL, `id_instance_class`=NULL, `field_caption`=NULL, `yii_model`='' WHERE `da_object`.`id_object`=94");
    $this->execute("UPDATE `da_object` SET `id_object`=60, `name`='Проверка файлов', `id_field_order`=NULL, `order_type`=1, `table_name`='yiigin/special/clearPreview', `id_field_caption`=NULL, `object_type`=3, `folder_name`='', `parent_object`=3, `sequence`=4, `seq_start_value`=1, `use_domain_isolation`=0, `id_object_handler`=NULL, `id_instance_class`=NULL, `field_caption`=NULL, `yii_model`='' WHERE `da_object`.`id_object`=60");
    $this->execute("UPDATE `da_object` SET `id_object`=91, `name`='Поисковый индекс', `id_field_order`=NULL, `order_type`=1, `table_name`='yiigin/special/recreateSearchIndex', `id_field_caption`=NULL, `object_type`=3, `folder_name`='', `parent_object`=3, `sequence`=3, `seq_start_value`=1, `use_domain_isolation`=0, `id_object_handler`=NULL, `id_instance_class`=NULL, `field_caption`=NULL, `yii_model`='' WHERE `da_object`.`id_object`=91");
    $this->execute("DELETE FROM `da_object_parameters` WHERE `da_object_parameters`.`id_object`=261 AND `da_object_parameters`.`id_parameter`=1316");
    $this->execute("DELETE FROM `da_object_parameters` WHERE `da_object_parameters`.`id_object`=260 AND `da_object_parameters`.`id_parameter`=1308");
    $this->execute("UPDATE `da_object_parameters` SET `id_object`=260, `id_parameter`=1307, `id_parameter_type`=10, `sequence`=9, `name`='statBanner', `caption`='Статистика', `field_name`='banners.yiigin.widgets.bannerStatistic.BannerStatisticWidget', `add_parameter`=2, `default_value`='', `not_null`=0, `sql_parameter`='BannerStatisticVisualElement', `is_unique`=0, `group_type`=0, `need_locale`=0, `search`=0, `is_additional`=0, `hint`='' WHERE `da_object_parameters`.`id_object`=260 AND `da_object_parameters`.`id_parameter`=1307");

    $path = dirname(__FILE__)."/../../assets/";
    HFile::removeDirectoryRecursive($path, false, false, false, array(".gitignore"));
  }

  public function safeDown() {
    echo get_class($this)." does not support migration down.\n";
    return false;
  }
}
