<?php

class m130607_171902_ygin extends CDbMigration {
  public function safeUp() {
    
    $this->execute("UPDATE `da_object` SET `id_object`='54', `name`='Доступные локализации', `id_field_order`='310', `order_type`=1, `table_name`='da_localization', `id_field_caption`='311', `object_type`=1, `folder_name`=NULL, `parent_object`=3, `sequence`=1, `use_domain_isolation`=0, `field_caption`='name', `yii_model`=NULL WHERE `da_object`.`id_object`='54'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=66 AND id_instance='74'");
    $this->execute("DELETE FROM `da_object_view_column` WHERE `da_object_view_column`.`id_object_view_column`='74'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=66 AND id_instance='75'");
    $this->execute("DELETE FROM `da_object_view_column` WHERE `da_object_view_column`.`id_object_view_column`='75'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=66 AND id_instance='76'");
    $this->execute("DELETE FROM `da_object_view_column` WHERE `da_object_view_column`.`id_object_view_column`='76'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=63 AND id_instance='36'");
    $this->execute("DELETE FROM `da_object_view` WHERE `da_object_view`.`id_object_view`='36'");
    $this->execute("UPDATE `da_object` SET `id_object`='55', `name`='Локализация данных', `id_field_order`='', `order_type`=1, `table_name`='da_localization_element', `id_field_caption`='', `object_type`=1, `folder_name`=NULL, `parent_object`=10, `sequence`=2, `use_domain_isolation`=0, `field_caption`='id_instance', `yii_model`=NULL WHERE `da_object`.`id_object`='55'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=21 AND id_instance='314'");
    $this->execute("DELETE FROM `da_object_parameters` WHERE `da_object_parameters`.`id_object`='55' AND `da_object_parameters`.`id_parameter`='314'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=21 AND id_instance='315'");
    $this->execute("DELETE FROM `da_object_parameters` WHERE `da_object_parameters`.`id_object`='55' AND `da_object_parameters`.`id_parameter`='315'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=21 AND id_instance='316'");
    $this->execute("DELETE FROM `da_object_parameters` WHERE `da_object_parameters`.`id_object`='55' AND `da_object_parameters`.`id_parameter`='316'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=21 AND id_instance='317'");
    $this->execute("DELETE FROM `da_object_parameters` WHERE `da_object_parameters`.`id_object`='55' AND `da_object_parameters`.`id_parameter`='317'");
    $this->execute("DELETE FROM da_domain_object WHERE id_object = '55'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=20 AND id_instance='55'");
    $this->execute("DELETE FROM `da_object` WHERE `da_object`.`id_object`='55'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=66 AND id_instance='77'");
    $this->execute("DELETE FROM `da_object_view_column` WHERE `da_object_view_column`.`id_object_view_column`='77'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=66 AND id_instance='78'");
    $this->execute("DELETE FROM `da_object_view_column` WHERE `da_object_view_column`.`id_object_view_column`='78'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=63 AND id_instance='37'");
    $this->execute("DELETE FROM `da_object_view` WHERE `da_object_view`.`id_object_view`='37'");
    $this->execute("UPDATE `da_object` SET `id_object`='57', `name`='Interface localization', `id_field_order`='', `order_type`=1, `table_name`='da_localization_interface', `id_field_caption`='', `object_type`=1, `folder_name`=NULL, `parent_object`=10, `sequence`=3, `use_domain_isolation`=0, `field_caption`='name', `yii_model`=NULL WHERE `da_object`.`id_object`='57'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=21 AND id_instance='321'");
    $this->execute("DELETE FROM `da_object_parameters` WHERE `da_object_parameters`.`id_object`='57' AND `da_object_parameters`.`id_parameter`='321'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=21 AND id_instance='320'");
    $this->execute("DELETE FROM `da_object_parameters` WHERE `da_object_parameters`.`id_object`='57' AND `da_object_parameters`.`id_parameter`='320'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=21 AND id_instance='319'");
    $this->execute("DELETE FROM `da_object_parameters` WHERE `da_object_parameters`.`id_object`='57' AND `da_object_parameters`.`id_parameter`='319'");
    $this->execute("DELETE FROM da_domain_object WHERE id_object = '57'");
    $this->execute("DELETE FROM `da_auth_item` WHERE name='create_object_57'");
    $this->execute("DELETE FROM `da_auth_item` WHERE name='delete_object_57'");
    $this->execute("DELETE FROM `da_auth_item` WHERE name='edit_object_57'");
    $this->execute("DELETE FROM `da_auth_item` WHERE name='list_object_57'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=20 AND id_instance='57'");
    $this->execute("DELETE FROM `da_object` WHERE `da_object`.`id_object`='57'");
    $this->execute("DELETE FROM da_domain_object WHERE id_object = '10'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=20 AND id_instance='10'");
    $this->execute("DELETE FROM `da_object` WHERE `da_object`.`id_object`='10'");
    $this->execute("UPDATE `da_object` SET `id_object`='527', `name`='Плагины системы', `id_field_order`='', `order_type`=1, `table_name`='da_plugin', `id_field_caption`='', `object_type`=1, `folder_name`='content/plugin', `parent_object`=3, `sequence`=0, `use_domain_isolation`=0, `field_caption`=NULL, `yii_model`=NULL WHERE `da_object`.`id_object`='527'");
    $this->execute("UPDATE `da_object` SET `id_object`='37', `name`='Файлы', `id_field_order`='134', `order_type`=1, `table_name`='da_files', `id_field_caption`='135', `object_type`=1, `folder_name`=NULL, `parent_object`=3, `sequence`=10, `use_domain_isolation`=0, `field_caption`='file_path', `yii_model`='ygin.models.File' WHERE `da_object`.`id_object`='37'");
    $this->execute("UPDATE `da_object` SET `id_object`='31', `name`='Домены сайта', `id_field_order`='281', `order_type`=1, `table_name`='da_domain', `id_field_caption`='283', `object_type`=1, `folder_name`='content/domain/', `parent_object`=3, `sequence`=20, `use_domain_isolation`=0, `field_caption`='name', `yii_model`='ygin.models.Domain' WHERE `da_object`.`id_object`='31'");
    $this->execute("UPDATE `da_object` SET `id_object`='531', `name`='Уведомления', `id_field_order`='1695', `order_type`=2, `table_name`='da_message', `id_field_caption`='1694', `object_type`=1, `folder_name`='content/messages', `parent_object`=3, `sequence`=50, `use_domain_isolation`=0, `field_caption`='text', `yii_model`='Message' WHERE `da_object`.`id_object`='531'");
    $this->execute("UPDATE `da_object` SET `id_object`='42', `name`='RSS', `id_field_order`='602', `order_type`=1, `table_name`='da_rss', `id_field_caption`='', `object_type`=1, `folder_name`=NULL, `parent_object`=1, `sequence`=10, `use_domain_isolation`=0, `field_caption`=NULL, `yii_model`=NULL WHERE `da_object`.`id_object`='42'");
    $this->execute("DELETE FROM da_domain_object WHERE id_object = '5'");
    $this->execute("DELETE FROM da_search_data WHERE id_object=20 AND id_instance='5'");
    $this->execute("DELETE FROM `da_object` WHERE `da_object`.`id_object`='5'");
    $this->execute("UPDATE `da_object` SET `id_object`='313', `name`='Настройка кэширования', `id_field_order`='', `order_type`=1, `table_name`='engine/admin/special/cacheSettings.php', `id_field_caption`='', `object_type`=3, `folder_name`=NULL, `parent_object`=1, `sequence`=1, `use_domain_isolation`=0, `field_caption`=NULL, `yii_model`=NULL WHERE `da_object`.`id_object`='313'");
    $this->execute("UPDATE `da_object` SET `id_object`='43', `name`='SQL', `id_field_order`='', `order_type`=1, `table_name`='backend/special/sql', `id_field_caption`='', `object_type`=3, `folder_name`=NULL, `parent_object`=1, `sequence`=5, `use_domain_isolation`=0, `field_caption`=NULL, `yii_model`=NULL WHERE `da_object`.`id_object`='43'");
    $this->execute("UPDATE `da_object` SET `id_object`='94', `name`='Логи', `id_field_order`='', `order_type`=1, `table_name`='backend/special/logView', `id_field_caption`='', `object_type`=3, `folder_name`=NULL, `parent_object`=1, `sequence`=12, `use_domain_isolation`=0, `field_caption`=NULL, `yii_model`=NULL WHERE `da_object`.`id_object`='94'");
    $this->execute("DELETE FROM `da_auth_item_child` WHERE parent='dev' AND child='view_object_94'");
    $this->execute("DELETE FROM `da_auth_item_child` WHERE parent='dev' AND child='list_object_94'");
    $this->execute("UPDATE `da_object` SET `id_object`='60', `name`='Проверка файлов', `id_field_order`='', `order_type`=1, `table_name`='backend/special/clearPreview', `id_field_caption`='', `object_type`=3, `folder_name`=NULL, `parent_object`=1, `sequence`=4, `use_domain_isolation`=0, `field_caption`=NULL, `yii_model`=NULL WHERE `da_object`.`id_object`='60'");
    $this->execute("UPDATE `da_object` SET `id_object`='89', `name`='Очистить кэш', `id_field_order`='', `order_type`=1, `table_name`='backend/special/clearCache', `id_field_caption`='', `object_type`=3, `folder_name`=NULL, `parent_object`=1, `sequence`=2, `use_domain_isolation`=0, `field_caption`=NULL, `yii_model`=NULL WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `id_object`='61', `name`='Инструкции', `id_field_order`='145', `order_type`=1, `table_name`='da_instruction', `id_field_caption`='141', `object_type`=1, `folder_name`=NULL, `parent_object`=1, `sequence`=6, `use_domain_isolation`=0, `field_caption`='name', `yii_model`=NULL WHERE `da_object`.`id_object`='61'");
    $this->execute("UPDATE `da_object` SET `id_object`='91', `name`='Поисковый индекс', `id_field_order`='', `order_type`=1, `table_name`='backend/special/recreateSearchIndex', `id_field_caption`='', `object_type`=3, `folder_name`=NULL, `parent_object`=1, `sequence`=3, `use_domain_isolation`=0, `field_caption`=NULL, `yii_model`=NULL WHERE `da_object`.`id_object`='91'");
    $this->execute("UPDATE `da_object` SET `sequence`=1 WHERE `da_object`.`id_object`='527'");
    $this->execute("UPDATE `da_object` SET `sequence`=2 WHERE `da_object`.`id_object`='30'");
    $this->execute("UPDATE `da_object` SET `sequence`=3 WHERE `da_object`.`id_object`='27'");
    $this->execute("UPDATE `da_object` SET `sequence`=4 WHERE `da_object`.`id_object`='29'");
    $this->execute("UPDATE `da_object` SET `sequence`=5 WHERE `da_object`.`id_object`='37'");
    $this->execute("UPDATE `da_object` SET `sequence`=6 WHERE `da_object`.`id_object`='31'");
    $this->execute("UPDATE `da_object` SET `sequence`=7 WHERE `da_object`.`id_object`='531'");
    $this->execute("UPDATE `da_object` SET `sequence`=8 WHERE `da_object`.`id_object`='54'");
    $this->execute("UPDATE `da_object` SET `sequence`=2 WHERE `da_object`.`id_object`='31'");
    $this->execute("UPDATE `da_object` SET `sequence`=3 WHERE `da_object`.`id_object`='30'");
    $this->execute("UPDATE `da_object` SET `sequence`=4 WHERE `da_object`.`id_object`='27'");
    $this->execute("UPDATE `da_object` SET `sequence`=5 WHERE `da_object`.`id_object`='29'");
    $this->execute("UPDATE `da_object` SET `sequence`=6 WHERE `da_object`.`id_object`='37'");
    $this->execute("UPDATE `da_object` SET `sequence`=6 WHERE `da_object`.`id_object`='531'");
    $this->execute("UPDATE `da_object` SET `sequence`=7 WHERE `da_object`.`id_object`='37'");
    $this->execute("UPDATE `da_object` SET `id_object`='1', `name`='Разработка', `id_field_order`='', `order_type`=1, `table_name`=NULL, `id_field_caption`='', `object_type`=1, `folder_name`=NULL, `parent_object`=NULL, `sequence`=3, `use_domain_isolation`=0, `field_caption`=NULL, `yii_model`=NULL WHERE `da_object`.`id_object`='1'");
    $this->execute("UPDATE `da_object` SET `sequence`=2 WHERE `da_object`.`id_object`='313'");
    $this->execute("UPDATE `da_object` SET `sequence`=4 WHERE `da_object`.`id_object`='91'");
    $this->execute("UPDATE `da_object` SET `sequence`=5 WHERE `da_object`.`id_object`='60'");
    $this->execute("UPDATE `da_object` SET `sequence`=6 WHERE `da_object`.`id_object`='43'");
    $this->execute("UPDATE `da_object` SET `sequence`=7 WHERE `da_object`.`id_object`='41'");
    $this->execute("UPDATE `da_object` SET `sequence`=8 WHERE `da_object`.`id_object`='61'");
    $this->execute("UPDATE `da_object` SET `sequence`=9 WHERE `da_object`.`id_object`='63'");
    $this->execute("UPDATE `da_object` SET `sequence`=11 WHERE `da_object`.`id_object`='94'");
    $this->execute("UPDATE `da_object` SET `sequence`=12 WHERE `da_object`.`id_object`='22'");
    $this->execute("UPDATE `da_object` SET `sequence`=13 WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `sequence`=12 WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `sequence`=13 WHERE `da_object`.`id_object`='51'");
    $this->execute("UPDATE `da_object` SET `sequence`=14 WHERE `da_object`.`id_object`='22'");
    $this->execute("UPDATE `da_object` SET `sequence`=11 WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `sequence`=12 WHERE `da_object`.`id_object`='51'");
    $this->execute("UPDATE `da_object` SET `sequence`=13 WHERE `da_object`.`id_object`='94'");
    $this->execute("UPDATE `da_object` SET `sequence`=10 WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `sequence`=11 WHERE `da_object`.`id_object`='51'");
    $this->execute("UPDATE `da_object` SET `sequence`=12 WHERE `da_object`.`id_object`='94'");
    $this->execute("UPDATE `da_object` SET `sequence`=13 WHERE `da_object`.`id_object`='42'");
    $this->execute("UPDATE `da_object` SET `sequence`=8 WHERE `da_object`.`id_object`='63'");
    $this->execute("UPDATE `da_object` SET `sequence`=9 WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `sequence`=10 WHERE `da_object`.`id_object`='51'");
    $this->execute("UPDATE `da_object` SET `sequence`=11 WHERE `da_object`.`id_object`='61'");
    $this->execute("UPDATE `da_object` SET `sequence`=7 WHERE `da_object`.`id_object`='63'");
    $this->execute("UPDATE `da_object` SET `sequence`=8 WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `sequence`=9 WHERE `da_object`.`id_object`='51'");
    $this->execute("UPDATE `da_object` SET `sequence`=10 WHERE `da_object`.`id_object`='61'");
    $this->execute("UPDATE `da_object` SET `sequence`=11 WHERE `da_object`.`id_object`='94'");
    $this->execute("UPDATE `da_object` SET `sequence`=12 WHERE `da_object`.`id_object`='42'");
    $this->execute("UPDATE `da_object` SET `sequence`=13 WHERE `da_object`.`id_object`='41'");
    $this->execute("UPDATE `da_object` SET `sequence`=2 WHERE `da_object`.`id_object`='80'");
    $this->execute("UPDATE `da_object` SET `sequence`=3 WHERE `da_object`.`id_object`='91'");
    $this->execute("UPDATE `da_object` SET `sequence`=4 WHERE `da_object`.`id_object`='60'");
    $this->execute("UPDATE `da_object` SET `sequence`=5 WHERE `da_object`.`id_object`='313'");
    $this->execute("UPDATE `da_object` SET `sequence`=5 WHERE `da_object`.`id_object`='43'");
    $this->execute("UPDATE `da_object` SET `sequence`=6 WHERE `da_object`.`id_object`='63'");
    $this->execute("UPDATE `da_object` SET `sequence`=7 WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `sequence`=8 WHERE `da_object`.`id_object`='51'");
    $this->execute("UPDATE `da_object` SET `sequence`=9 WHERE `da_object`.`id_object`='61'");
    $this->execute("UPDATE `da_object` SET `sequence`=10 WHERE `da_object`.`id_object`='94'");
    $this->execute("UPDATE `da_object` SET `sequence`=11 WHERE `da_object`.`id_object`='42'");
    $this->execute("UPDATE `da_object` SET `sequence`=12 WHERE `da_object`.`id_object`='313'");
    $this->execute("UPDATE `da_object` SET `sequence`=5 WHERE `da_object`.`id_object`='63'");
    $this->execute("UPDATE `da_object` SET `sequence`=6 WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `sequence`=7 WHERE `da_object`.`id_object`='51'");
    $this->execute("UPDATE `da_object` SET `sequence`=8 WHERE `da_object`.`id_object`='43'");
    $this->execute("UPDATE `da_object` SET `sequence`=6 WHERE `da_object`.`id_object`='51'");
    $this->execute("UPDATE `da_object` SET `sequence`=7 WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `sequence`=4 WHERE `da_object`.`id_object`='63'");
    $this->execute("UPDATE `da_object` SET `sequence`=5 WHERE `da_object`.`id_object`='51'");
    $this->execute("UPDATE `da_object` SET `sequence`=6 WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `sequence`=7 WHERE `da_object`.`id_object`='43'");
    $this->execute("UPDATE `da_object` SET `sequence`=8 WHERE `da_object`.`id_object`='60'");
    $this->execute("UPDATE `da_object` SET `sequence`=3 WHERE `da_object`.`id_object`='63'");
    $this->execute("UPDATE `da_object` SET `sequence`=4 WHERE `da_object`.`id_object`='51'");
    $this->execute("UPDATE `da_object` SET `sequence`=5 WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `sequence`=6 WHERE `da_object`.`id_object`='91'");
    $this->execute("UPDATE `da_object` SET `id_object`='89', `name`='Кэш, индексы', `id_field_order`='', `order_type`=1, `table_name`='backend/special/clearCache', `id_field_caption`='', `object_type`=3, `folder_name`=NULL, `parent_object`=1, `sequence`=5, `use_domain_isolation`=0, `field_caption`=NULL, `yii_model`=NULL WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `id_object`='91', `name`='Поисковый индекс', `id_field_order`='', `order_type`=1, `table_name`='backend/special/recreateSearchIndex', `id_field_caption`='', `object_type`=3, `folder_name`=NULL, `parent_object`=1, `sequence`=6, `use_domain_isolation`=0, `field_caption`=NULL, `yii_model`=NULL WHERE `da_object`.`id_object`='91'");
    $this->execute("INSERT IGNORE INTO `da_auth_item` (`name`, `type`, `description`, `bizrule`, `data`) VALUES ('view_object_91', 0, 'Операция просмотра для объекта Поисковый индекс', NULL, 'N;')");
    $this->execute("INSERT IGNORE INTO `da_auth_item_child` (`parent`, `child`) VALUES ('dev', 'view_object_91')");
    $this->execute("INSERT IGNORE INTO `da_auth_item` (`name`, `type`, `description`, `bizrule`, `data`) VALUES ('list_object_91', 0, 'Просмотр списка данных объекта Поисковый индекс', NULL, 'N;')");
    $this->execute("INSERT IGNORE INTO `da_auth_item_child` (`parent`, `child`) VALUES ('dev', 'list_object_91')");
    $this->execute("UPDATE `da_object` SET `id_object`='89', `name`='Сброс кэша', `id_field_order`='', `order_type`=1, `table_name`='backend/special/clearCache', `id_field_caption`='', `object_type`=3, `folder_name`=NULL, `parent_object`=1, `sequence`=5, `use_domain_isolation`=0, `field_caption`=NULL, `yii_model`=NULL WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object_parameters` SET `id_object`='63', `id_parameter`='409', `id_parameter_type`=9, `sequence`=7, `widget`=NULL, `caption`='Видимость в панели', `field_name`='visible', `add_parameter`='0', `default_value`='1', `not_null`=1, `sql_parameter`=NULL, `is_unique`=0, `group_type`=0, `need_locale`=0, `search`=0, `is_additional`=0, `hint`='' WHERE `da_object_parameters`.`id_object`='63' AND `da_object_parameters`.`id_parameter`='409'");
    $this->execute("UPDATE `da_object_view` SET `id_object_view`='50', `id_object`='80', `name`='php-скрипты', `order_no`=1, `visible`=0, `sql_select`=NULL, `sql_from`=NULL, `sql_where`=NULL, `sql_order_by`='id_php_script_type ASC', `count_data`=50, `icon_class`=NULL, `id_parent`=NULL WHERE `da_object_view`.`id_object_view`='50'");
    $this->execute("INSERT INTO `da_reference_element` (`id_reference`, `id_reference_element`, `id_reference_element_instance`, `value`, `image_element`) VALUES ('31', 5, 'ygin.object.reference.type.link', 'Ссылка', NULL)");
    $this->execute("INSERT INTO `da_object` (`order_type`, `object_type`, `sequence`, `use_domain_isolation`, `parent_object`, `id_object`, `name`, `table_name`, `folder_name`, `field_caption`, `id_field_caption`, `id_field_order`, `yii_model`) VALUES (1, '5', 0, 0, 1, 'ygin.override', 'Переопределение представлений (debug=true)', '/override/', NULL, NULL, '', '', NULL)");
    $this->execute("INSERT INTO `da_auth_item` (`name`, `type`, `description`, `bizrule`, `data`) VALUES ('view_object_ygin.override', 0, 'Операция просмотра для объекта Переопределение представлений (debug=true)', NULL, 'N;')");
    $this->execute("INSERT INTO `da_auth_item_child` (`parent`, `child`) VALUES ('dev', 'view_object_ygin.override')");
    $this->execute("INSERT INTO `da_auth_item` (`name`, `type`, `description`, `bizrule`, `data`) VALUES ('list_object_ygin.override', 0, 'Просмотр списка данных объекта Переопределение представлений (debug=true)', NULL, 'N;')");
    $this->execute("INSERT INTO `da_auth_item_child` (`parent`, `child`) VALUES ('dev', 'list_object_ygin.override')");
    $this->execute("UPDATE da_object SET sequence = 50 WHERE id_object='ygin.override'");
    $this->execute("UPDATE `da_object` SET `sequence`=5 WHERE `da_object`.`id_object`='ygin.override'");
    $this->execute("UPDATE `da_object` SET `sequence`=6 WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `sequence`=7 WHERE `da_object`.`id_object`='91'");
    $this->execute("UPDATE `da_object` SET `sequence`=8 WHERE `da_object`.`id_object`='43'");
    $this->execute("UPDATE `da_object` SET `sequence`=9 WHERE `da_object`.`id_object`='60'");
    $this->execute("UPDATE `da_object` SET `sequence`=10 WHERE `da_object`.`id_object`='61'");
    $this->execute("UPDATE `da_object` SET `sequence`=11 WHERE `da_object`.`id_object`='94'");
    $this->execute("UPDATE `da_object` SET `sequence`=12 WHERE `da_object`.`id_object`='42'");
    $this->execute("UPDATE `da_object` SET `sequence`=13 WHERE `da_object`.`id_object`='313'");
    $this->execute("UPDATE `da_object` SET `sequence`=14 WHERE `da_object`.`id_object`='41'");
    $this->execute("UPDATE `da_object` SET `sequence`=15 WHERE `da_object`.`id_object`='22'");
    $this->execute("INSERT INTO `da_object` (`order_type`, `object_type`, `sequence`, `use_domain_isolation`, `parent_object`, `id_object`, `name`, `table_name`, `folder_name`, `field_caption`, `id_field_caption`, `id_field_order`, `yii_model`) VALUES (1, 5, 0, 0, 1, 'ygin.gii', 'gii (debug=true)', '/gii/', NULL, NULL, '', '', NULL)");
    $this->execute("INSERT INTO `da_auth_item` (`name`, `type`, `description`, `bizrule`, `data`) VALUES ('view_object_ygin.gii', 0, 'Операция просмотра для объекта gii (debug=true)', NULL, 'N;')");
    $this->execute("INSERT INTO `da_auth_item_child` (`parent`, `child`) VALUES ('dev', 'view_object_ygin.gii')");
    $this->execute("INSERT INTO `da_auth_item` (`name`, `type`, `description`, `bizrule`, `data`) VALUES ('list_object_ygin.gii', 0, 'Просмотр списка данных объекта gii (debug=true)', NULL, 'N;')");
    $this->execute("INSERT INTO `da_auth_item_child` (`parent`, `child`) VALUES ('dev', 'list_object_ygin.gii')");
    $this->execute("UPDATE da_object SET sequence = 50 WHERE id_object='ygin.gii'");
    $this->execute("UPDATE `da_object` SET `sequence`=6 WHERE `da_object`.`id_object`='ygin.gii'");
    $this->execute("UPDATE `da_object` SET `sequence`=7 WHERE `da_object`.`id_object`='89'");
    $this->execute("UPDATE `da_object` SET `sequence`=8 WHERE `da_object`.`id_object`='91'");
    $this->execute("UPDATE `da_object` SET `sequence`=9 WHERE `da_object`.`id_object`='43'");
    $this->execute("UPDATE `da_object` SET `sequence`=10 WHERE `da_object`.`id_object`='60'");
    $this->execute("UPDATE `da_object` SET `sequence`=11 WHERE `da_object`.`id_object`='61'");
    $this->execute("UPDATE `da_object` SET `sequence`=12 WHERE `da_object`.`id_object`='94'");
    $this->execute("UPDATE `da_object` SET `sequence`=13 WHERE `da_object`.`id_object`='42'");
    $this->execute("UPDATE `da_object` SET `sequence`=14 WHERE `da_object`.`id_object`='313'");
    $this->execute("UPDATE `da_object` SET `sequence`=15 WHERE `da_object`.`id_object`='41'");
    $this->execute("UPDATE `da_object` SET `sequence`=16 WHERE `da_object`.`id_object`='22'");

    $path = dirname(__FILE__)."/../../assets/";
    @HFile::removeDirectoryRecursive($path, false, false, false, array(".gitignore"));
  }

  public function safeDown() {
    echo get_class($this)." does not support migration down.\n";
    return false;
  }
}
